/** Declaration file generated by dts-gen */

declare module 'socketio-file-upload' {

	export = socketio_file_upload;

	function socketio_file_upload(options: any): any;

	namespace socketio_file_upload {
	    const clientPath: string;

	    function listen(app: any): void;

	    function router(req: any, res: any, next: any): void;

	}
}
